---
services: docker
sudo: required
language: python
python:
  - '2.7'

env:
  - OPENSHIFT_VERSION=latest
  - OPENSHIFT_VERSION=v3.9

script:
  # Download test shim.
  - wget -O ${PWD}/apb-test.sh https://raw.githubusercontent.com/djzager/apb-test-shim/master/apb-test.sh
  - chmod +x ${PWD}/apb-test.sh

  # Run tests.
  - ${PWD}/apb-test.sh

# notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
